<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>lss</string>
   </array>
  <key>name</key>
  <string>luascript</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.luascript</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(final|static)\b)</string>
          <key>name</key>
          <string>keyword.luascript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>source.luascript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#declaration_structure</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#declaration_variable</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#declaration_function</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.luascript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.luascript</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.luascript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.luascript</string>
        </dict>
       </array>
    </dict>
    <key>comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>declaration_function</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\b(func)\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.luascript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#declaration_function__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\{$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\b(init)(?=\())</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.luascript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#declaration_function__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>declaration_function__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\-\&gt;)</string>
          <key>name</key>
          <string>support.constant.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w+(?=(:|\s*=)))</string>
          <key>name</key>
          <string>variable.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w+)(?=\()</string>
          <key>name</key>
          <string>entity.name.function.luascript</string>
        </dict>
       </array>
    </dict>
    <key>declaration_function__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w+(?=(:|\s*=)))</string>
          <key>name</key>
          <string>variable.luascript</string>
        </dict>
       </array>
    </dict>
    <key>declaration_structure</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\b(extension|class)\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.luascript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#declaration_structure__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\{$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\b(enum)\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.luascript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#declaration_structure__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\}$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>declaration_structure__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(?&lt;!(:|,)\s*)(\w+)(?=(:|\s*\{))\b)</string>
          <key>name</key>
          <string>entity.class.name.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(\w+)\b)</string>
          <key>name</key>
          <string>entity.other.inherited-class.luascript</string>
        </dict>
       </array>
    </dict>
    <key>declaration_structure__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(\w+)(?=\s*\{))</string>
          <key>name</key>
          <string>entity.class.name.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(\w+)\b)</string>
          <key>name</key>
          <string>constant.other.luascript</string>
        </dict>
       </array>
    </dict>
    <key>declaration_variable</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\b(var|let)\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.luascript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#declaration_variable__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.luascript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>declaration_variable__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(var|let)\b)</string>
          <key>name</key>
          <string>keyword.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w+(?=(:|\s*=)))</string>
          <key>name</key>
          <string>variable.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w+)(?=\()</string>
          <key>name</key>
          <string>support.function.luascript</string>
        </dict>
       </array>
    </dict>
    <key>lua</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\b(function)\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.luascript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#lua__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>source.luascript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;![^.]\.|:)\b(false|nil|true|_G|_VERSION|math\.(pi|huge))\b|(?&lt;![.])\.{3}(?!\.)</string>
          <key>name</key>
          <string>constant.language.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;![^.]\\.|:)\b(self)\b</string>
          <key>name</key>
          <string>support.other.variable.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;![^.]\.|:)\b(false|nil|true|_G|_VERSION|math\.(pi|huge))\b|(?&lt;![.])\.{3}(?!\.)</string>
          <key>name</key>
          <string>constant.language.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(break|do|else|for|if|elseif|goto|return|then|repeat|while|until|end|function|local|in|and|or|not)\b)</string>
          <key>name</key>
          <string>keyword.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([a-zA-Z_][a-zA-Z0-9_]*)\b(?=\s*(?:[\x{0028}\x{007b}\&quot;\x{0027}]|\[\[))</string>
          <key>name</key>
          <string>support.function.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;=[^.]\.|:)\b([a-zA-Z_][a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>variable.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;![^.]\.|:)\\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall)\b(?=\s*(?:[\x{0028}\x{007b}\&quot;\x{0027}]|\[\[))</string>
          <key>name</key>
          <string>support.function.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;![^.]\.|:)\b(coroutine\.(create|resume|running|status|wrap|yield)|string\.(byte|char|dump|find|format|gmatch|gsub|len|lower|match|rep|reverse|sub|upper)|table\.(concat|insert|maxn|remove|sort)|math\.(abs|acos|asin|atan2?|ceil|cosh?|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|pow|rad|random|randomseed|sinh?|sqrt|tanh?)|io\.(close|flush|input|lines|open|output|popen|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|package\.(cpath|loaded|loadlib|path|preload|seeall)|debug\.(debug|[gs]etfenv|[gs]ethook|getinfo|[gs]etlocal|[gs]etmetatable|getregistry|[gs]etupvalue|traceback))\b(?=\s*(?:[\x{0028}\x{007b}\&quot;\x{0027}]|\[\[))</string>
          <key>name</key>
          <string>support.function.luascript</string>
        </dict>
       </array>
    </dict>
    <key>lua__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w+(?=(:|\s*=)))</string>
          <key>name</key>
          <string>variable.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w+)(?=\()</string>
          <key>name</key>
          <string>entity.name.function.luascript</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>source.luascript</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\.?\d+\b)</string>
          <key>name</key>
          <string>constant.numeric.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b0x([0-9a-fA-F]{3,6})+\b)</string>
          <key>name</key>
          <string>constant.numeric.luascript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;([0-9a-fA-F]{3,6})+)\b</string>
          <key>name</key>
          <string>constant.numeric.luascript</string>
        </dict>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.luascript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.luascript</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.luascript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.luascript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.luascript</string>
          <key>end</key>
          <string>(\&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.luascript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.luascript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.luascript</string>
          <key>end</key>
          <string>(\]\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.luascript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>string__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>string__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>string__3</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>types</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(string|number|boolean|table|function|userdata|class|object|any))</string>
          <key>name</key>
          <string>support.type.luascript</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
