<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>lss</string>
   </array>
  <key>name</key>
  <string>LuaScript</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.LuaScript</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b((import|final|override|static|let|var)\s)</string>
          <key>name</key>
          <string>keyword.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;=(import)\s)([\w\.]+)</string>
          <key>name</key>
          <string>storage.LuaScript</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#enums</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#structures</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#text</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#variables</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\=|\=\=|~\=|&gt;|&gt;\=|&lt;|&lt;\=|%%|-&gt;)</string>
          <key>name</key>
          <string>keyword.operator.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.LuaScript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.LuaScript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.LuaScript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.LuaScript</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>enums</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>((enum)\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#enums__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>enums__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\w+)(?=\s*\{)</string>
          <key>name</key>
          <string>entity.name.class.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)(?=,?)</string>
          <key>name</key>
          <string>constant.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>lua</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(break|do|else|for|if|elseif|goto|return|then|repeat|while|until|end|function|local|in|try|catch)\b</string>
          <key>name</key>
          <string>keyword.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(and|or|not)\b</string>
          <key>name</key>
          <string>keyword.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(false|nil|true|_G|_VERSION|math\.(pi|huge))</string>
          <key>name</key>
          <string>constant.language.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(coroutine\.(create|resume|running|status|wrap|yield)|string\.(byte|char|dump|find|format|gmatch|gsub|len|lower|match|rep|reverse|sub|upper)|table\.(concat|insert|maxn|remove|sort)|math\.(abs|acos|asin|atan2?|ceil|cosh?|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|pow|rad|random|randomseed|sinh?|sqrt|tanh?)|io\.(close|flush|input|lines|open|output|popen|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|package\.(cpath|loaded|loadlib|path|preload|seeall)|debug\.(debug|[gs]etfenv|[gs]ethook|getinfo|[gs]etlocal|[gs]etmetatable|getregistry|[gs]etupvalue|traceback))\b</string>
          <key>name</key>
          <string>support.function.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\s?(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall))</string>
          <key>name</key>
          <string>support.function.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#text</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#lua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)(?=\s*)</string>
          <key>name</key>
          <string>variable.parameter.LuaScript</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#variables</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(?&lt;![.\d])\d+(?:\.\d+)+(?![.\d])</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([0x]([a-fA-F0-9]{3,6})+)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{0026}]([a-fA-F0-9]{3,6})+)</string>
          <key>name</key>
          <string>constant.numeric.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>structures</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>((extension|class)\s*)(?=(\w+):\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#structures__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\s*\{)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(extension|class)(?=\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#structures__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(:|\{)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(func)(?=\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.LuaScript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#structures__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\()</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>structures__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\w+)(?=:)</string>
          <key>name</key>
          <string>entity.name.class.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>entity.other.inherited-class.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>structures__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>entity.name.class.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>structures__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>entity.name.function.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>text</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.LuaScript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.LuaScript</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.LuaScript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.LuaScript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.LuaScript</string>
          <key>end</key>
          <string>(\&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.LuaScript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>text__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>text__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>types</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((?!(:|\s))(string|number|boolean|table|function|userdata|enum|extension|class|object|any)(?=(\?|,|\)|\s|=)))</string>
          <key>name</key>
          <string>support.type.LuaScript</string>
        </dict>
       </array>
    </dict>
    <key>variables</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(init)(?=\()</string>
          <key>name</key>
          <string>keyword.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;=(:|\.|\s))(\w+)(?=\()</string>
          <key>name</key>
          <string>function.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(self)(?=(.|:))</string>
          <key>name</key>
          <string>constant.other.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)(?=:\s*)</string>
          <key>name</key>
          <string>variable.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?&lt;=\.)(\w+)</string>
          <key>name</key>
          <string>variable.LuaScript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)(?=\.)</string>
          <key>name</key>
          <string>variable.LuaScript</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
